---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ako
  namespace: your-namespace
spec:
  interval: 5m
  chart:
    spec:
      chart: ako/ako
      version: "1.5.2"
      sourceRef:
        kind: HelmRepository
        name: ako
        namespace: flux-system
  values:
    # Aquí van tus valores personalizados. Por ejemplo:
    controllerSettings:
      controllerVersion: "20.1.3"
