---
ingress:
  enabled: true
  virtual_host_fqdn: "prometheus-test.uva.es"
  prometheus_prefix: "/"
  alertmanager_prefix: "/alertmanager/"
  prometheusServicePort: 80
  alertmanagerServicePort: 80
prometheus:
  pvc:
    storageClassName: vsphere-tanzu
alertmanager:
  pvc:
    storageClassName: vsphere-tanzu
